### PR TITLE
Create cta section and fix small issues

### LINKED ISSUE #72: Create CTA section
image

### PR DESCRIPTION
**Pull request by mhevyk**
Created call to action (cta) section

image

Also made following changes:
1. Fixed variable names in `AppButton.scss`
2. Added global `AppTypography` property to wrap text to new line if we add `\n` in translations
3. Replaced `AppFooter.test.jsx` to `AppFooter.test.tsx`
4. Renamed `subintro.scss` to `Subintro.scss`

### CODE REVIEW

File: code/src/pages/home/HomePage.tsx [hunk 1]
```diff
@@ -3,16 +3,19 @@ import IntroBanner from "@/layouts/intro-banner/IntroBanner";
 import PageWrapper from "@/layouts/page-wrapper/PageWrapper";
 import Subintro from "@/layouts/subintro/Subintro";
 import CategorySection from "@/layouts/category-section/CategorySection";
+import CallToActionSection from "@/pages/home/components/call-to-action-section/CallToActionSection";
 
 const HomePage = () => {
   return (
     <>
       <IntroBanner />
+      <CallToActionSection />
```
Comment (D1nviz) [inline code/src/pages/home/HomePage.tsx]: move it below subintro section

File: code/src/pages/home/components/call-to-action-section/CallToAction.test.tsx [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import { render, screen } from "@testing-library/react";
+import CallToActionSection from "@/pages/home/components/call-to-action-section/CallToActionSection";
+import { MemoryRouter } from "react-router-dom";
```
Comment (D1nviz) [inline code/src/pages/home/components/call-to-action-section/CallToAction.test.tsx]: organize imports

File: code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+type CallToActionSectionItemProps = {
+  titleTranslationKey: string;
+  descriptionTranslationKey: string;
+  captionTranslationKey: string;
+  linkTo: string;
+  imageUrl: string;
+  buttonLabelTranslationKey: string;
+};
+
+const CallToActionSectionItem = ({
```
Comment (D1nviz) [inline code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx]: move it to separate component

File: code/src/pages/home/HomePage.tsx [hunk 4]
```diff
@@ -3,16 +3,19 @@ import IntroBanner from "@/layouts/intro-banner/IntroBanner";
...
       <PageWrapper>
         <Subintro />
         <BestSellers />
         <CategorySection />
       </PageWrapper>
+      <PageWrapper>Content</PageWrapper>
```
Comment (D1nviz) [inline code/src/pages/home/HomePage.tsx]: remove it

File: code/src/pages/home/components/call-to-action-section/CallToAction.test.tsx (hunk 2 above)
Comment (mhevyk) [reply code/src/pages/home/components/call-to-action-section/CallToAction.test.tsx]: Fixed

File: code/src/pages/home/HomePage.tsx (hunk 1 above)
Comment (mhevyk) [reply code/src/pages/home/HomePage.tsx]: Makes sense. I did it

File: code/src/pages/home/HomePage.tsx (hunk 4 above)
Comment (mhevyk) [reply code/src/pages/home/HomePage.tsx]: Removed, it is not needed anymore

File: code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+          />
+        </AppButton>
+      </AppLink>
+    </AppBox>
+  );
+};
+
+const CallToActionSection = () => {
+  return (
+    <AppContainer maxWidth="xl" className="call-to-action">
```
Comment (D1nviz) [inline code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx]: Also, I suggest not using AppContainer with maxWidth prop. We already have page wrapper with max-width

File: code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx (hunk 3 above)
Comment (mhevyk) [reply code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx]: Moved. Please check if i got you correctly

File: code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx (hunk 5 above)
Comment (mhevyk) [reply code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx]: Replaced with `AppBox`

**Review by D1nviz — APPROVED** [review]

File: code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx (hunk 3 above)
Comment (D1nviz) [reply code/src/pages/home/components/call-to-action-section/CallToActionSection.tsx]: Yeah, that's it

**Review by heshvab — APPROVED** [review]

File: code/src/layouts/call-to-action/CallToAction.scss [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+  flex-direction: column;
+
+  @include breakpoint("lg") {
+    flex-direction: row;
+  }
+
+  &__item {
+    flex-basis: 100%;
+    padding: spacing(14);
+    background-color: red;
```
Comment (dmtrth25) [inline code/src/layouts/call-to-action/CallToAction.scss]: `red` use variables

File: code/src/layouts/call-to-action/CallToAction.tsx [hunk 7]
```diff
@@ -0,0 +1,18 @@
+import AppBox from "@/components/app-box/AppBox";
+import CallToActionItem from "@/layouts/call-to-action/components/call-to-action-item/CallToActionItem";
+
```
Comment (dmtrth25) [inline code/src/layouts/call-to-action/CallToAction.tsx]: remove space

File: code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+  descriptionTranslationKey,
+  captionTranslationKey,
+  buttonLabelTranslationKey,
+  linkTo,
+  imageUrl
+}: CallToActionSectionItemProps) => {
+  return (
+    <AppBox
+      className="call-to-action__item"
+      sx={{ backgroundImage: `url(${imageUrl})` }}
```
Comment (dmtrth25) [inline code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx:26]: for now we configured `webpack` with opportunity to write `bg image` inside `scss`
try to rewrite

File: code/src/layouts/call-to-action/CallToAction.scss (hunk 6 above)
Comment (mhevyk) [reply code/src/layouts/call-to-action/CallToAction.scss]: Thanks a lot @dmtrth25, i really forgot to remove it after some local testing. This was removed

File: code/src/layouts/call-to-action/CallToAction.tsx (hunk 7 above)
Comment (mhevyk) [reply code/src/layouts/call-to-action/CallToAction.tsx]: Removed space

File: code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx (hunk 8 above)
Comment (mhevyk) [reply code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx:26]: I know about new `webpack` config, you did a really great job! I thought it would be better if we can store our images inside constants for that folder and not inside scss. What do you think about that?

**Review by ValKoDim — APPROVED** [review]

File: code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx (hunk 8 above)
Comment (dmtrth25) [reply code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx:26]: > I know about new `webpack` config, you did a really great job! I thought it would be better if we can store our images inside constants for that folder and not inside scss. What do you think about that?

Not sure. But for now we replaced using inline styles to `scss`. We should to discuss it. Or rewrite existing approach with bg image for our `banner` at the home page. And follow one approach as well

**Review by dmtrth25 — APPROVED** [review]
