### PR TITLE
Fixed checkbox bug

### LINKED ISSUE #476: Fix product form checkbox bug
There is some bug with checkbox in product form. I guess it occurs due to incorrect approach of using react hook form and checkboxes, checked is not passed.

### PR DESCRIPTION
**Pull request by heshvab**
- Fixed checkbox bug
- Added additional tag so products are refetched after manager updates product

### CODE REVIEW

File: code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx [hunk 1]
```diff
@@ -56,6 +57,29 @@ const AdditionalInfo = ({
     </>
   );
 
+  const checkboxControllerRenderFunction = ({
+    field: { onChange, ...props }
+  }: {
+    field: ControllerRenderProps<ProductFormValues>;
+  }) => {
```
Comment (mhevyk) [inline code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx]: Move type to separate variable for better readability

**Review by mhevyk — APPROVED** [review]

**Review by D1nviz — APPROVED** [review]

**Review by dmtrth25 — APPROVED** [review]

File: code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx (hunk 1 above)
Comment (heorhiiss) [reply code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx]: Fixed
