### PR TITLE
Fix sorting arrows on manager orders tab

### LINKED ISSUE #382: Fix sorting arrows on manager orders tab
When we click on some sort we should either hide other arrows or make their arrows return to initial state because we can have only one sort in row
Change the colour of currently working sort
Colored initial filter

image

### PR DESCRIPTION
**Pull request by OliaHrytsak**
Changed acteve sort color, not active sort direction
Added default sort 

https://github.com/user-attachments/assets/a5468db4-02f8-4f10-8cc4-bf8672c24626

image

### CODE REVIEW

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx [hunk 1]
```diff
@@ -30,29 +30,45 @@ const OrdersTableHead = ({ head }: OrderTableHeadProps) => {
...
-      const newSort = `${sortKey},${newSortDirection}`;
-      const params = new URLSearchParams(searchParams);
-      params.set("sort", newSort);
-      setSearchParams(params);
+    let newSortDirection: SortOrder;
+
+    if (isActive) {
+      newSortDirection = sortDirections[sortKey] === "desc" ? "asc" : "desc";
+    } else {
+      newSortDirection = initialSortOrder[sortKey] === "desc" ? "asc" : "desc";
```
Comment (D1nviz) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: You can refactor it to smth like that
`newSortDirection = (isActive ? sortDirections[sortKey] : initialSortOrder[sortKey]) === "desc" ? "asc" : "desc";`

File: code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts [hunk 2]
```diff
@@ -24,7 +24,9 @@ const useFilteredAdminOrders = () => {
 
   const [searchParams] = useSearchParams();
 
-  const sortParam = searchParams.get("sort") as SortOrder | null;
+  const sortParam = searchParams.get("sort") as SortOrder;
+
+  console.log("hook calls");
```
Comment (D1nviz) [inline code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts]: remove this `log`

Comment (OliaHrytsak) [reply code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts]: Removed

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx (hunk 1 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Done! Thanks

File: code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts [hunk 3]
```diff
@@ -54,6 +54,7 @@ describe("useFilteredAdminOrders", () => {
       new URLSearchParams(),
       mockSetSearchParams
     ]);
+    jest.clearAllMocks();
```
Comment (mhevyk) [inline code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts]: Why we need it? We mock everything and then clear all mocks. Maybe we can move it to `afterEach` or remove completely?

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx [hunk 4]
```diff
@@ -22,62 +22,46 @@ const sortableFields = [
 describe("OrderTableHead", () => {
   beforeEach(() => {
     (useSearchParams as jest.Mock).mockReturnValue([
-      new URLSearchParams(),
+      new URLSearchParams(`sort=${"createdAt,desc"}`),
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Remove template literal

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx [hunk 5]
```diff
@@ -86,16 +70,97 @@ describe("OrderTableHead", () => {
...
+    await waitFor(() => {
+      params = new URLSearchParams(mockSetSearchParams.mock.calls[2][0]);
+      expect(params.get("sort")).toBe("total,asc");
+    });
+
+    fireEvent.click(sortButtonCreatedAt);
+    await waitFor(() => {
+      params = new URLSearchParams(mockSetSearchParams.mock.calls[3][0]);
+      expect(params.get("sort")).toBe("createdAt,asc");
+    });
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Try to reuse this logic. Maybe create function that will perform step by index

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx [hunk 6]
```diff
@@ -86,16 +70,97 @@ describe("OrderTableHead", () => {
...
 
-    fireEvent.click(sortButton);
-    expect(sortButton).toHaveClass("MuiTableSortLabel-iconDirectionDesc");
+    fireEvent.click(sortButtonCreatedAt);
+    await waitFor(() => {
+      expect(mockSetSearchParams).toHaveBeenCalledWith(
+        new URLSearchParams({ sort: "createdAt,asc" })
+      );
+    });
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Create some helper for it, it is repeated

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx [hunk 7]
```diff
@@ -30,29 +30,43 @@ const OrdersTableHead = ({ head }: OrderTableHeadProps) => {
...
-      const newSort = `${sortKey},${newSortDirection}`;
-      const params = new URLSearchParams(searchParams);
-      params.set("sort", newSort);
-      setSearchParams(params);
-    }
+    const newSortDirection =
+      (isActive ? sortDirections[sortKey] : initialSortOrder[sortKey]) ===
+      "desc"
+        ? "asc"
+        : "desc";
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Split into two separate variables, avoid nested ternaries

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx [hunk 8]
```diff
@@ -30,29 +30,43 @@ const OrdersTableHead = ({ head }: OrderTableHeadProps) => {
...
+    setSearchParams(params);
   };
 
-  const sortDirection = sortKey && sortDirections[sortKey];
+  useEffect(() => {
+    if (!searchParams.has("sort")) {
+      const newSearchParams = new URLSearchParams(searchParams);
+      newSearchParams.set("sort", "createdAt,desc");
+      setSearchParams(newSearchParams);
+    }
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Also create local helper for it:

```tsx
 const params = new URLSearchParams(searchParams);
    params.set("sort", newSort);
    setSearchParams(params);
```

**Review by D1nviz — APPROVED** [review]

**Review by heshvab — APPROVED** [review]

File: code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts (hunk 3 above)
Comment (OliaHrytsak) [reply code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts]: Removed

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx (hunk 4 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Removed

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx (hunk 5 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Created helper func to avoid code repeating

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx (hunk 6 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx]: Created helper function too) Thank you for advice

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx (hunk 7 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Splited!

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx (hunk 8 above)
Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Created! Looks better.

File: code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx [hunk 9]
```diff
@@ -30,29 +30,46 @@ const OrdersTableHead = ({ head }: OrderTableHeadProps) => {
...
+    updateSearchParams(sortKey, newSortDirection);
   };
 
-  const sortDirection = sortKey && sortDirections[sortKey];
+  useEffect(() => {
+    if (!searchParams.has("sort")) {
+      const newSearchParams = new URLSearchParams(searchParams);
+      newSearchParams.set("sort", "createdAt,desc");
+      setSearchParams(newSearchParams);
+    }
```
Comment (mhevyk) [inline code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Try to reuse `updateSearchParams`

Comment (OliaHrytsak) [reply code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx]: Reused! Thanks a lot!

**Review by mhevyk — APPROVED** [review]
