### PR TITLE
Fixed the request issue to backend. Changed the infinite value to 1000

### LINKED ISSUE #372: Fix sorting for product categories
Currently when we filter products by their categories and we try to apply sorting on those products, user is redirected back to all products page.

### LINKED ISSUE #374: Products doesn't load from DB
We get an error 400, when we try to request products from DB. 
Screenshot 2024-07-25 at 10 31 40

### PR DESCRIPTION
**Pull request by ValKoDim**
Fixed the request to backend by changing the size of the list of requested products. Also fixed sorting for categories.

### CODE REVIEW

File: code/src/pages/products/ProductsPage.tsx [hunk 1]
```diff
@@ -43,7 +43,9 @@ const ProductsPage = () => {
   );
 
   const handleSortChange = (value: string) => {
-    setSearchParams({ sort: value });
+    searchParams.delete("sort");
+    searchParams.append("sort", value);
```
Comment (mhevyk) [inline code/src/pages/products/ProductsPage.tsx]: Use `searchParams.set("sort");`

Comment (ValKoDim) [reply code/src/pages/products/ProductsPage.tsx]: I have made that change

**Review by mhevyk — APPROVED** [review]

**Review by D1nviz — APPROVED** [review]

**Review by OliaHrytsak — APPROVED** [review]

**Review by heshvab — APPROVED** [review]

**Review by dmtrth25 — APPROVED** [review]
